generated_at: 2026-07-07
pve_host: dieSehnsucht
machines: 
    - id: 100
      kind: lxc
      name: OpenWrt
      status: running
      pve_host: dieSehnsucht
      os: OpenWrt
      managed_by: pve-cfg/openwrt
      vlan: null
      zone: null
      address_configured: 192.168.10.10/24
      address_observed: 192.168.10.10/24
      gateway: 192.168.10.1
      bridge: vmbr0
      onboot: true
      unprivileged: false
      rootfs: "local-lvm:vm-100-disk-1,size=1G"
      memory_mb: 512
      cores: 2
    - id: 101
      kind: lxc
      name: Nginx
      status: running
      pve_host: dieSehnsucht
      os: debian
      managed_by: ansible-cfg
      vlan: 30
      zone: nginx_zone
      address_configured: 192.168.30.2/24
      address_observed: 192.168.30.2/24
      gateway: 192.168.30.1
      bridge: vmbr0
      onboot: true
      unprivileged: true
      rootfs: "local-lvm:vm-101-disk-0,size=10G"
      memory_mb: 512
      cores: 1
    - id: 102
      kind: lxc
      name: Tunnel
      status: running
      pve_host: dieSehnsucht
      os: debian
      managed_by: ansible-cfg
      vlan: 40
      zone: tunnel_zone
      address_configured: 192.168.40.2/24
      address_observed: 192.168.40.2/24
      gateway: 192.168.40.1
      bridge: vmbr0
      onboot: true
      unprivileged: true
      rootfs: "local-lvm:vm-102-disk-0,size=2G"
      memory_mb: 256
      cores: 1
    - id: 103
      kind: lxc
      name: Monitor
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 60
      zone: monitor_zone
      address_configured: 192.168.60.2/24
      address_observed: null
      gateway: 192.168.60.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-103-disk-0,size=20G"
      memory_mb: 1024
      cores: 4
    - id: 104
      kind: lxc
      name: Jenkins
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 100
      zone: cicd_zone
      address_configured: 192.168.100.2/24
      address_observed: null
      gateway: 192.168.100.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-104-disk-0,size=200G"
      memory_mb: 4096
      cores: 4
    - id: 105
      kind: lxc
      name: Gitlab
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 110
      zone: git_zone
      address_configured: 192.168.110.2/24
      address_observed: null
      gateway: 192.168.110.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-105-disk-0,size=100G"
      memory_mb: 16384
      cores: 4
    - id: 106
      kind: lxc
      name: Coolify
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 100
      zone: cicd_zone
      address_configured: 192.168.100.3/24
      address_observed: null
      gateway: 192.168.100.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-106-disk-0,size=100G"
      memory_mb: 8192
      cores: 4
    - id: 107
      kind: lxc
      name: Gitea
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 110
      zone: git_zone
      address_configured: 192.168.110.3/24
      address_observed: null
      gateway: 192.168.110.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-107-disk-0,size=50G"
      memory_mb: 4096
      cores: 2
    - id: 108
      kind: lxc
      name: Mirror
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 30
      zone: nginx_zone
      address_configured: 192.168.30.3/24
      address_observed: null
      gateway: 192.168.30.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-108-disk-0,size=10G"
      memory_mb: 512
      cores: 1
    - id: 109
      kind: lxc
      name: NextCloud
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.8/24
      address_observed: null
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-109-disk-0,size=50G"
      memory_mb: 4096
      cores: 4
    - id: 110
      kind: lxc
      name: Plex
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 120
      zone: media_zone
      address_configured: 192.168.120.2/24
      address_observed: null
      gateway: 192.168.120.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-110-disk-0,size=9G"
      memory_mb: 4096
      cores: 2
    - id: 111
      kind: lxc
      name: Navidrome
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 120
      zone: media_zone
      address_configured: 192.168.120.3/24
      address_observed: null
      gateway: 192.168.120.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-111-disk-0,size=10G"
      memory_mb: 512
      cores: 1
    - id: 112
      kind: lxc
      name: CodeRunner
      status: running
      pve_host: dieSehnsucht
      os: debian
      managed_by: ansible-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.11/24
      address_observed: 192.168.50.11/24
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: true
      unprivileged: true
      rootfs: "local-lvm:vm-112-disk-0,size=310G"
      memory_mb: 8192
      cores: 6
    - id: 113
      kind: lxc
      name: Kuma
      status: running
      pve_host: dieSehnsucht
      os: debian
      managed_by: ansible-cfg
      vlan: 60
      zone: monitor_zone
      address_configured: 192.168.60.3/24
      address_observed: 192.168.60.3/24
      gateway: 192.168.60.1
      bridge: vmbr0
      onboot: true
      unprivileged: true
      rootfs: "local:113/vm-113-disk-0.raw,size=5G"
      memory_mb: 512
      cores: 1
    - id: 114
      kind: lxc
      name: VSCode
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.12/24
      address_observed: null
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-114-disk-0,size=20G"
      memory_mb: 8192
      cores: 4
    - id: 115
      kind: lxc
      name: Coder
      status: running
      pve_host: dieSehnsucht
      os: debian
      managed_by: ansible-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.13/24
      address_observed: 192.168.50.13/24
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: true
      unprivileged: true
      rootfs: "local-lvm:vm-115-disk-0,size=10G"
      memory_mb: 2048
      cores: 2
    - id: 146
      kind: lxc
      name: tyz
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 66
      zone: user_zone
      address_configured: 192.168.66.5/24
      address_observed: null
      gateway: 192.168.66.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-146-disk-0,size=20G"
      memory_mb: 4096
      cores: 2
    - id: 147
      kind: lxc
      name: lyf
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 66
      zone: user_zone
      address_configured: 192.168.66.4/24
      address_observed: null
      gateway: 192.168.66.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-147-disk-0,size=20G"
      memory_mb: 4096
      cores: 2
    - id: 148
      kind: lxc
      name: sty
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 66
      zone: user_zone
      address_configured: 192.168.66.3/24
      address_observed: null
      gateway: 192.168.66.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-148-disk-0,size=40G"
      memory_mb: 4096
      cores: 2
    - id: 149
      kind: lxc
      name: test
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 66
      zone: user_zone
      address_configured: 192.168.66.2/24
      address_observed: null
      gateway: 192.168.66.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-149-disk-0,size=5G"
      memory_mb: 512
      cores: 1
    - id: 150
      kind: lxc
      name: Monogatari
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.2/24
      address_observed: null
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-150-disk-0,size=10G"
      memory_mb: 512
      cores: 1
    - id: 151
      kind: lxc
      name: edu-ai
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.3/24
      address_observed: null
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-151-disk-0,size=260G"
      memory_mb: 8192
      cores: 6
    - id: 152
      kind: lxc
      name: bot-diesw
      status: running
      pve_host: dieSehnsucht
      os: debian
      managed_by: ansible-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.4/24
      address_observed: 192.168.50.4/24
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: true
      unprivileged: true
      rootfs: "local-lvm:vm-152-disk-0,size=20G"
      memory_mb: 4096
      cores: 4
    - id: 153
      kind: lxc
      name: bot-desuwa
      status: running
      pve_host: dieSehnsucht
      os: debian
      managed_by: ansible-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.5/24
      address_observed: 192.168.50.5/24
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: true
      unprivileged: true
      rootfs: "local-lvm:vm-153-disk-0,size=20G"
      memory_mb: 4096
      cores: 4
    - id: 154
      kind: lxc
      name: pan
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 80
      zone: storage_zone
      address_configured: 192.168.80.3/24
      address_observed: null
      gateway: 192.168.80.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-154-disk-0,size=10G"
      memory_mb: 256
      cores: 1
    - id: 155
      kind: lxc
      name: LiteratureReview
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.6/24
      address_observed: null
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-155-disk-0,size=50G"
      memory_mb: 4096
      cores: 2
    - id: 156
      kind: lxc
      name: seiii-eval
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.7/24
      address_observed: null
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-156-disk-0,size=30G"
      memory_mb: 4096
      cores: 2
    - id: 157
      kind: lxc
      name: CodexManager
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.9/24
      address_observed: null
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-157-disk-0,size=10G"
      memory_mb: 512
      cores: 1
    - id: 158
      kind: lxc
      name: sub2api
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 50
      zone: app_zone
      address_configured: 192.168.50.10/24
      address_observed: null
      gateway: 192.168.50.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-158-disk-0,size=10G"
      memory_mb: 2048
      cores: 4
    - id: 197
      kind: vm
      name: NixOS
      status: running
      pve_host: dieSehnsucht
      os: l26
      managed_by: nixos-cfg
      vlan: 50
      zone: app_zone
      address_configured: null
      address_observed: null
      bridge: vmbr0
      onboot: false
      memory_mb: 8192
      cores: 4
      bootdisk: 100.00
    - id: 198
      kind: vm
      name: DockerHost
      status: running
      pve_host: dieSehnsucht
      os: "Debian GNU/Linux 12 (bookworm)"
      managed_by: ansible-cfg
      vlan: 50
      zone: app_zone
      address_configured: null
      address_observed: 192.168.50.14/24
      bridge: vmbr0
      onboot: true
      memory_mb: 8192
      cores: 4
      bootdisk: 100.00
    - id: 199
      kind: vm
      name: DSM
      status: running
      pve_host: dieSehnsucht
      os: l26
      managed_by: manual-or-image-backup
      vlan: 80
      zone: storage_zone
      address_configured: null
      address_observed: 192.168.80.2/24
      bridge: vmbr0
      onboot: false
      memory_mb: 8192
      cores: 4
      bootdisk: 3.50
    - id: 200
      kind: lxc
      name: seiii
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 67
      zone: group_zone
      address_configured: 192.168.67.2/24
      address_observed: null
      gateway: 192.168.67.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-200-disk-0,size=50G"
      memory_mb: 4096
      cores: 2
    - id: 300
      kind: lxc
      name: PostgreSQL
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 90
      zone: db_zone
      address_configured: 192.168.90.2/24
      address_observed: null
      gateway: 192.168.90.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-300-disk-0,size=10G"
      memory_mb: 512
      cores: 1
    - id: 301
      kind: lxc
      name: Redis
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 90
      zone: db_zone
      address_configured: 192.168.90.3/24
      address_observed: null
      gateway: 192.168.90.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-301-disk-0,size=10G"
      memory_mb: 512
      cores: 1
    - id: 302
      kind: lxc
      name: MySQL
      status: stopped
      pve_host: dieSehnsucht
      os: debian
      managed_by: pve-cfg
      vlan: 90
      zone: db_zone
      address_configured: 192.168.90.4/24
      address_observed: null
      gateway: 192.168.90.1
      bridge: vmbr0
      onboot: false
      unprivileged: true
      rootfs: "local-lvm:vm-302-disk-0,size=10G"
      memory_mb: 512
      cores: 1
