
bios: ovmf
boot: order=scsi0;ide2;net0
cores: 4
cpu: x86-64-v2-AES
efidisk0: local-lvm:vm-197-disk-0,efitype=4m,size=4M
ide2: local:iso/nixos-graphical-26.05.4193.a50de1b7d8a5-x86_64-linux.iso,media=cdrom,size=3731904K
machine: q35
memory: 8192
meta: creation-qemu=10.1.2,ctime=1783391445
name: NixOS
net0: virtio=BC:24:11:6C:34:6F,bridge=vmbr0,firewall=1,tag=50
numa: 0
ostype: l26
scsi0: local-lvm:vm-197-disk-1,discard=on,iothread=1,size=100G,ssd=1
scsihw: virtio-scsi-single
smbios1: uuid=cd3fc428-5271-4373-9899-d43e9f723b6e
sockets: 1
vmgenid: 957b357f-81a5-4976-9926-c8e1a018e539
