
agent: 1,fstrim_cloned_disks=1
balloon: 0
bios: ovmf
boot: order=sata0;scsi0
cores: 4
cpu: host
efidisk0: local-lvm:vm-199-disk-0,efitype=4m,size=4M
ide2: none,media=cdrom
machine: q35
memory: 8192
meta: creation-qemu=10.1.2,ctime=1775894745
name: DSM
net0: virtio=BC:24:11:77:CC:93,bridge=vmbr0,firewall=1,tag=80
numa: 0
ostype: l26
sata0: local-lvm:vm-199-disk-1,size=3588M
scsi0: local-lvm:vm-199-disk-2,discard=on,iothread=1,size=1000G,ssd=1
scsihw: virtio-scsi-single
serial0: socket
smbios1: uuid=ff55e677-8fbd-490f-815c-cff3ec20d5d9
sockets: 1
vmgenid: 1bf3ab28-fbc2-4ecc-a7d0-bfe373acde63
