
arch: amd64
cores: 1
features: nesting=1
hostname: Tunnel
memory: 256
nameserver: 8.8.8.8 1.1.1.1
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.40.1,hwaddr=BC:24:11:7C:72:D8,ip=192.168.40.2/24,tag=40,type=veth
onboot: 1
ostype: debian
rootfs: local-lvm:vm-102-disk-0,size=2G
swap: 256
unprivileged: 1
